/**
 * Emscripten-glue bridge loader.
 *
 * chili-wasm.js is a single-file build of OCCT generated by Emscripten. It
 * exports a default factory `MainModuleFactory(options?)` that asynchronously
 * instantiates the module. We fetch the file from /wasm/ (served by Vite's
 * public/ directory) alongside the .wasm binary, then call the factory with
 * an explicit `wasmBinary` so we don't pay for a second fetch.
 */

export interface MainModule {
  Converter: {
    convertFromStep(bytes: Uint8Array): { shape: unknown; name: string; color?: string; getChildren?: () => unknown[] } | undefined;
    convertFromIges(bytes: Uint8Array): { shape: unknown; name: string; color?: string; getChildren?: () => unknown[] } | undefined;
    convertFromStl(bytes: Uint8Array): { shape: unknown; name: string; color?: string; getChildren?: () => unknown[] } | undefined;
    convertToStep(shapes: Array<{ shape: unknown }>): string;
    convertToIges(shapes: Array<{ shape: unknown }>): string;
    convertToBrep(shape: { shape: unknown }): string;
    convertFromBrep(brep: string): unknown;
  };
  ShapeFactory: {
    box(...args: unknown[]): unknown;
    cylinder(...args: unknown[]): unknown;
    sphere(...args: unknown[]): unknown;
    // ...many more exported but only used types matter:
  };
  Mesher: new (shape: unknown, deflection: number, useBoxRatio: boolean) => {
    mesh(): {
      faceMeshData: {
        position: Array<number>;
        normal: Array<number>;
        uv: Array<number>;
        index: Array<number>;
        group: Array<number>;
        faces: Array<unknown>;
      };
      edgeMeshData: {
        position: Array<number>;
        group: Array<number>;
        edges: Array<unknown>;
      };
    };
    delete(): void;
  };
  Shape: {
    boundingBox(shape: unknown, useMesh: boolean): { min: { x: number; y: number; z: number }; max: { x: number; y: number; z: number } };
    findSubShapes(shape: unknown, kind: number): Array<unknown>;
    getDirectSubShapes(shape: unknown): Array<unknown>;
    ptr(shape: unknown): number;
  };
  TopAbs_ShapeEnum: {
    TopAbs_VERTEX: { value: 7 };
    TopAbs_EDGE: { value: 6 };
    TopAbs_WIRE: { value: 5 };
    TopAbs_FACE: { value: 4 };
    TopAbs_SHELL: { value: 3 };
    TopAbs_SOLID: { value: 2 };
    TopAbs_COMPOUND: { value: 0 };
    TopAbs_COMPSOLID: { value: 1 };
    TopAbs_SHAPE: { value: 8 };
  };
  TopAbs_Orientation: {
    TopAbs_FORWARD: { value: 0 };
    TopAbs_REVERSED: { value: 1 };
    TopAbs_INTERNAL: { value: 2 };
    TopAbs_EXTERNAL: { value: 3 };
  };
}

type EmscriptenFactory = (options?: { wasmBinary?: ArrayBuffer | Uint8Array }) => Promise<MainModule>;

let initPromise: Promise<MainModule> | null = null;

/**
 * Initialize the OCCT WASM module. Idempotent: subsequent calls return the
 * same Promise / module.
 */
export function initWasm(): Promise<MainModule> {
  if (initPromise) return initPromise;
  initPromise = (async () => {
    // Vite serves /wasm/* from src/renderer/public/wasm/* (no bundling needed).
    //
    //  V1.30 — @ts-expect-error: wildcards in global.d.ts ('/wasm/*',
    //  '*chili-wasm.js', literal) fail to match under bundler resolution.
    const mod: { default: EmscriptenFactory } = await import(
      // @ts-expect-error - Vite-served absolute /wasm/* URL
      /* @vite-ignore */ "/wasm/chili-wasm.js"
    );
    const wasmBinary = await fetch("/wasm/chili-wasm.wasm").then((r) =>
      r.arrayBuffer(),
    );
    const m = await mod.default({ wasmBinary });
    // Emscripten factory sets this when we pass { wasmBinary } directly, but
    // we still publish globally for any module that reads raw `wasm.foo`.
    globalThis.wasm = m;
    return m;
  })();
  return initPromise;
}
